#server:
#  port: 8081
#spring:
#  profiles:
#    active: dev
#---
#server:
#  port: 8083
#spring:
#  profiles: dev
#---
#server:
#  port: 8084
#spring:
#  profiles: prod


#--- 三个横线表示一个文档块:用来分割不同环境的文档

#  注意:port:后面的这个空格不能少
#  ""不会转义特殊字符
#  ''会转义特殊字符

#person:
#  age: 18
#  boss: false
#  birth: 2019/01/24
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2
#  lastName: zhangsan
  spring: 
  profiles:
    active:
      - dev
--- 
server:
    port: 8001
  spring: 
     profiles: dev
     application: 
      name: microservicecloud-config-dept-client
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloudDB01
      username: root
      password: 123456
    dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200 
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml


  eureka: 
    client: #客户端注册进eureka服务列表内
      service-url: 
        defaultZone: http://eureka7001.com:7001/eureka
  instance:
      instance-id: dept-8001.com
      prefer-ip-address: true


info:
    app.name: atguigu-microservicecloud-springcloudconfig01
    company.name: www.atguigu.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$






---
server:
    port: 8001
  spring: 
     profiles: test
     application: 
      name: microservicecloud-config-dept-client




   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloudDB02
      username: root
      password: 123456
    dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200  
    
    
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml


  eureka: 
    client: #客户端注册进eureka服务列表内
      service-url: 
        defaultZone: http://eureka7001.com:7001/eureka
  instance:
      instance-id: dept-8001.com
      prefer-ip-address: true


info:
    app.name: atguigu-microservicecloud-springcloudconfig02
    company.name: www.atguigu.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$

